-- SUPABASE SETUP FOR REAL VISITOR COUNT + ON-SITE MESSAGES
-- Run this SQL in Supabase SQL Editor.

create table if not exists public.site_stats (
  id bigint primary key,
  visitors bigint not null default 0
);

insert into public.site_stats (id, visitors)
values (1, 0)
on conflict (id) do nothing;

create or replace function public.increment_visitors()
returns void
language sql
security definer
set search_path = public
as $$
  update public.site_stats
  set visitors = visitors + 1
  where id = 1;
$$;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- Enable RLS
alter table public.site_stats enable row level security;
alter table public.messages enable row level security;

-- Visitors can read the public counter.
create policy "public can read visitor count"
on public.site_stats
for select
to anon
using (true);

-- The website can insert messages.
create policy "public can send messages"
on public.messages
for insert
to anon
with check (
  char_length(name) between 1 and 80
  and char_length(email) between 3 and 120
  and char_length(message) between 1 and 1000
);

-- Allow the public RPC to increment the count.
grant execute on function public.increment_visitors() to anon;
grant select on public.site_stats to anon;
grant insert on public.messages to anon;
